### PR TITLE
chore(Incubator): Remove stable apps from catalog

### PR DESCRIPTION
**Pull request by StevenMcElligott**
**Description**

Deleted old incubator apps from the catalog that have been moved to stable already, thought it was automatic but godo to get rid of stuff after 2 months

⚒️ Fixes  # 

**⚙️ Type of change**

- [X] ⚙️ Feature/App addition
- [X] 🪛 Bugfix
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🔃 Refactor of current code

**🧪 How Has This Been Tested?**

**📃 Notes:**

**✔️ Checklist:**

- [ ] ⚖️ My code follows the style guidelines of this project
- [ ] 👀 I have performed a self-review of my own code
- [ ] #️⃣ I have commented my code, particularly in hard-to-understand areas
- [ ] 📄 I have made corresponding changes to the documentation
- [ ] ⚠️ My changes generate no new warnings
- [ ] 🧪 I have added tests to this description that prove my fix is effective or that my feature works
- [ ] ⬆️ I increased versions for any altered app according to semantic versioning

**➕ App addition**

If this PR is an app addition please make sure you have done the following.

- [ ] 🪞 I have opened a PR on [truecharts/containers](https://github.com/truecharts/containers) adding the container to TrueCharts mirror repo.
- [ ] 🖼️ I have added an icon in the Chart's root directory called `icon.png`

---

_Please don't blindly check all the boxes. Read them and only check those that apply.
Those checkboxes are there for the reviewer to see what is this all about and
the status of this PR with a quick glance._

### CODE REVIEW

**Comment by StevenMcElligott** [comment]
> speedtest-tracker is still in incubator I believe (hasnt yet been moved to stable)

https://github.com/truecharts/charts/tree/master/charts/stable/speedtest-exporter

I got it here, went according to the PR's mentionning `Stable` inside /charts

**Comment by StevenMcElligott** [comment]
Lol too many speedtests for me

**Review by Ornias1993 — CHANGES_REQUESTED** [review]
You edited the wrong branch. Please only edit the staging branch.

**Comment by StevenMcElligott** [comment]
> You edited the wrong branch. Please only edit the staging branch.

Fixed! (Hopefully lol)

**Pull request merged**
